yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='index'),  
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank = True,
        null = True,
        on_delete = models.CASCADE,
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Post, Group

def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 
    

def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context) 

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru"> 
  

  <head>  
    {% block title %}   
    {% endblock %}  
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>

    
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href={% url 'posts:index' %}>
          <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
      </div>
</nav>      

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% extends 'base.html'%}  
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">


    <title>
      {% block title %}
        Записи сообщества {{ group.title }}
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
    </header>

    
    <main>
      {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      {% for post in posts %}
      <div class="container py-5">
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if not forloop.last %}<hr>{% endif %}
        <h1>{{ text_2 }}</h1>
      </div>
      {% endfor %}
      {% endblock %}  
    </main>
    <footer class="page-footer font-small blue border-top">
    </footer>
  </body>
</html>

yatube/templates/posts/index.html
<!DOCTYPE html> 
<html lang="ru">
  <head>
  </head>
  <body>
    <h1>Главная страница</h1>
  </body>
</html> 